region: us-east-2

function_name: know_before_current_state
handler: apis.lambda_handler
description: Task used to update the kb4 current state.
runtime: python3.6
role: lambda_basic_execution
timeout: 30
memory_size: 512
environment_variables:
  API_URL: ${API_URL}
  API_TOKEN: ${API_TOKEN}
  GSHEETS_FILE_ID: ${GSHEETS_FILE_ID}
  GSHEETS_SA: ${GSHEETS_SA}
